proglbl -> PROGRAM
  TOKEN: PROGRAM	 LEXEME: program
Traceback (most recent call last):
  File "/Users/ewillard/dev/school/cs5500/hw1/miplParser.py", line 597, in vardecpart
    raise NoViableAltException(self)
antlr4.error.Errors.NoViableAltException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mipl.py", line 230, in <module>
    main(sys.argv)
  File "mipl.py", line 227, in main
    tree = parser.prog()
  File "/Users/ewillard/dev/school/cs5500/hw1/miplParser.py", line 424, in prog
    self.block()
  File "/Users/ewillard/dev/school/cs5500/hw1/miplParser.py", line 520, in block
    self.vardecpart()
  File "/Users/ewillard/dev/school/cs5500/hw1/miplParser.py", line 601, in vardecpart
    self._errHandler.reportError(self, re)
  File "/Users/ewillard/dev/school/cs5500/hw1/cs5500/lib/python3.6/site-packages/antlr4/error/ErrorStrategy.py", line 124, in reportError
    self.reportNoViableAlternative(recognizer, e)
  File "/Users/ewillard/dev/school/cs5500/hw1/cs5500/lib/python3.6/site-packages/antlr4/error/ErrorStrategy.py", line 250, in reportNoViableAlternative
    recognizer.notifyErrorListeners(msg, e.offendingToken, e)
  File "/Users/ewillard/dev/school/cs5500/hw1/cs5500/lib/python3.6/site-packages/antlr4/Parser.py", line 314, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "/Users/ewillard/dev/school/cs5500/hw1/cs5500/lib/python3.6/site-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "mipl.py", line 219, in syntaxError
    raise Exception("SYNTAX ERROR ON LINE " + str(line) + "!!! \n" + " --> What the heck is '" +offendingSymbol.text + "' ?")
Exception: SYNTAX ERROR ON LINE 6!!! 
 --> What the heck is '*' ?
